spring.application.name=abc_bank

server.port=${SERVER_PORT:8090}

#MySQL Database Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bank}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#JWT Configuration
jwt.secret.string=${JWT_SECRET:}
jwt.expirtation.time=${JWT_EXPIRATION_MS:2592000000}


#Mail Configuration
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}


spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}

#Enable TLS SMTP MAIL

spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
